# Generated by Django 5.2.15 on 2026-07-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectedservice',
            old_name='account_email',
            new_name='account_id',
        ),
    ]
