# Generated by Django 5.2.15 on 2026-07-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectedservice',
            old_name='accessToken',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='connectedservice',
            old_name='refreshToken',
            new_name='refresh_token',
        ),
    ]
